from bot.handlers.home import (
    create_home_router,
    handle_home_callback,
    handle_search_callback,
    handle_contribute_callback,
    handle_about_callback,
    handle_contact_callback,
    handle_tools_callback,
    handle_admin_panel_callback,
    handle_back_callback,
)
from bot.handlers.sections import (
    create_sections_router,
    handle_sections_callback,
    handle_section_view_callback,
    handle_section_back_callback,
    handle_section_admin_add,
    handle_section_admin_edit,
    handle_section_admin_set_order,
    handle_section_admin_delete,
    handle_section_admin_confirm_delete,
    handle_section_admin_cancel,
    handle_section_skip_desc,
)
from bot.handlers.fallback import create_fallback_router

__all__ = [
    "create_home_router",
    "create_sections_router",
    "create_fallback_router",
    "handle_home_callback",
    "handle_sections_callback",
    "handle_section_view_callback",
    "handle_section_back_callback",
    "handle_section_admin_add",
    "handle_section_admin_edit",
    "handle_section_admin_set_order",
    "handle_section_admin_delete",
    "handle_section_admin_confirm_delete",
    "handle_section_admin_cancel",
    "handle_section_skip_desc",
    "handle_search_callback",
    "handle_contribute_callback",
    "handle_about_callback",
    "handle_contact_callback",
    "handle_tools_callback",
    "handle_admin_panel_callback",
    "handle_back_callback",
]
